In [1]:
import pandas as pd
import numpy as np
import seaborn as sns

In [9]:
colnames = ['Preg', 'Glu', 'Bp', 'Sft', 'Ins', 'Bmi', 'Dpf', 'Age', 'outcome']
#Load the file from local directory using pd.read_csv which is a special form of read_table
#while reading the data, supply the "colnames" list
df = pd.read_csv("diabetes.csv")

In [6]:
df.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [10]:
df.columns = colnames

In [11]:
df.head()

Preg  Glu  Bp  Sft  Ins   Bmi    Dpf  Age  outcome
0     6  148  72   35    0  33.6  0.627   50        1
1     1   85  66   29    0  26.6  0.351   31        0
2     8  183  64    0    0  23.3  0.672   32        1
3     1   89  66   23   94  28.1  0.167   21        0
4     0  137  40   35  168  43.1  2.288   33        1

In [12]:
X = df.drop(['outcome'],axis =1)
y = df['outcome']

In [13]:
from sklearn.model_selection import train_test_split

In [20]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=2)

In [21]:
from sklearn.tree import DecisionTreeClassifier

In [28]:
m1 = DecisionTreeClassifier(criterion='entropy',random_state=0)

In [29]:
m1.fit(X_train,y_train)

DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=0,
            splitter='best')

In [30]:
pred = m1.predict(X_test)

In [31]:
from sklearn.metrics import confusion_matrix,accuracy_score

In [35]:
print(confusion_matrix(pred,y_test))

[[122  41]
 [ 33  35]]


In [34]:
accuracy_score(pred,y_test)

0.6796536796536796

In [36]:
d1 = pd.DataFrame(m1.feature_importances_,columns =['Imp'],index = X_train.columns)

In [37]:
d1

Imp
Preg  0.089866
Glu   0.257847
Bp    0.112757
Sft   0.036992
Ins   0.052421
Bmi   0.194523
Dpf   0.168654
Age   0.086940

In [38]:
from sklearn.model_selection import GridSearchCV
param = {'max_depth':np.arange(1,10)}
gd = GridSearchCV(m1,param,cv =3)
gd.fit(X,y)

GridSearchCV(cv=3, error_score='raise-deprecating',
       estimator=DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=0,
            splitter='best'),
       fit_params=None, iid='warn', n_jobs=None,
       param_grid={'max_depth': array([1, 2, 3, 4, 5, 6, 7, 8, 9])},
       pre_dispatch='2*n_jobs', refit=True, return_train_score='warn',
       scoring=None, verbose=0)

In [39]:
gd.best_params_

{'max_depth': 4}

In [58]:
m2 = DecisionTreeClassifier(criterion='entropy',max_depth=4,random_state=0)
m2.fit(X_train,y_train)

DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=4,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=0,
            splitter='best')

In [59]:
pred1 = m2.predict(X_test)

In [60]:
print(confusion_matrix(pred1,y_test))

[[125  23]
 [ 30  53]]


In [61]:
accuracy_score(pred1,y_test)

0.7705627705627706

In [62]:
m3 = DecisionTreeClassifier(criterion='gini',max_depth=4,random_state=0)
m3.fit(X_train,y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=4,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=0,
            splitter='best')

In [63]:
pred2 = m3.predict(X_test)

In [64]:
print(confusion_matrix(pred2,y_test))

[[135  40]
 [ 20  36]]


In [65]:
print(accuracy_score(pred2,y_test))

0.7402597402597403
